manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: ryo-k-k                          # <--- add this
      url-base: https://github.com/ryo-k-k/prospector-zmk-module.git    # <--- and this
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
    - name: prospector-zmk-module                 # <--- and these
      remote: ryo-k-k                        # <---
      revision: main                              # <---
  self:
    path: config
