on: [push, pull_request, workflow_dispatch]
    - name: Remove BOM from all .overlay files
      run: |
        find . -name "*.overlay" -exec sed -i '1s/^\xEF\xBB\xBF//' {} +

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
